# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd2edda921984fadcb22cf7c6abef552847e3c10ab11c5c1e5ab5855a3e7920a8480ba9d74fe555f7460da56e879f3241de58756734b23c5577e4256fa50deef

test:
  secret_key_base: 29027ee551ca485988119968172d7dfdcc2b8fe4d72ab71ac07cd0118bea8c80cbc3d21deeacb63476ef55db3cc002f8b67d80db2b788e959c3855643aa10b0c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
